---
- name: configure ec2 
  hosts: slave-node
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Download HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add HashiCorp repository
      apt_repository:
        repo: deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        state: present
        filename: 'hashicorp'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Terraform
      apt:
        name: terraform
        state: present

    - name: Download and install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Jenkins directory
      file:
        path: /home/ubuntu/jenkins
        state: directory
        owner: ubuntu
        group: ubuntu


