---
- name: Configure private EC2 to be a private agent
  hosts: private-app
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt cache after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install SSH server
      apt:
        name: openssh-server
        state: present

    - name: Create Jenkins directory
      file:
        path: /home/ubuntu/jenkins
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0777'

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Add ubuntu user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
