---
- name: configure private ec2 to be private agent
  hosts: private-app
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Download and install Docker
      apt:
        name: docker-ce
        state: present

    - name: Download and install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Jenkins directory
      file:
        path: /home/ubuntu/jenkins
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Download and install Git
      apt:
        name: git
        state: present

    - name: Add user to the 'docker' group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create 'jenkins' user
      user:
        name: jenkins
        state: present
        groups: docker
        append: yes

    - name: Ensure jenkins user can connect to Docker socket
      become: yes
      file:
        path: /var/run/docker.sock
        group: docker
        mode: '0777'
